included:
- CNILAssistant
excluded:
- Pods

disabled_rules: # rule identifiers to exclude from running
  - todo
  - force_cast
  - identifier_name

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 15
  error: 20
line_length:
  warning: 150
  error: 200
function_parameter_count:
  warning: 10
function_body_length:
  warning: 100
  error: 160
file_length:
  warning: 1000
  error: 1500
type_body_length:
  warning: 400
  error: 500
